" syntax highlighting
syntax on

" usually using dark terminal backgrounds
set background=dark

" set the obvious
set autoindent

" 72 character columns
set textwidth=72

" row and column and bottom right
set ruler

" highlight matching text in searches
set hls

" paste toggle
set pastetoggle=<F12>

" always show 3 top/bottom lines when scrolling
set scrolloff=3

" better backspace
set backspace=indent,eol,start

" Always reformat lines/paragraphs to textwidth
" set formatoptions+=a

" apply different settings for different file extensions
autocmd BufNewFile,BufRead *.html setlocal tabstop=4 softtabstop=4 textwidth=0
autocmd BufNewFile,BufRead *.css setlocal tabstop=4 softtabstop=4 textwidth=0
autocmd BufNewFile,BufRead *.json setlocal tabstop=2 softtabstop=2 textwidth=0
autocmd BufNewFile,BufRead *.py,*.py.* setlocal tabstop=4 softtabstop=4 textwidth=0 expandtab syntax=python
autocmd BufNewFile,BufRead *.hcl,*.tf,*.tfvars setlocal tabstop=2 softtabstop=2 expandtab textwidth=0 syntax=tf
autocmd BufNewFile,BufRead *.txt setlocal tabstop=4 softtabstop=4 expandtab
autocmd BufNewFile,BufRead *.yml,*.yml.*,*.yaml,*.yaml.* setlocal tabstop=2 softtabstop=2 textwidth=0 expandtab syntax=yaml

" copy/paste between vim instances by using tmp file
vmap \y :w! /tmp/vimshare<CR>
nmap \y :w! /tmp/vimshare<CR>
nmap \p :r! cat /tmp/vimshare<CR>
