alias cd-git-root='cd "$(git rev-parse --show-toplevel)"'
alias k8s='kubectl config use-context $(kubectl config get-contexts -o name | fzf)'
alias kube='export KUBECONFIG=$(find -L ~/.kube -type f -name "*.kube*" -o -name "*.yml" | fzf)'
alias nvim-config='nvim ~/.config/nvim/init.lua'
alias nvim-plugins='nvim ~/.config/nvim/lua/plugins'
alias repo='cd $(find -L ${HOME}/git -maxdepth 4 -type d -name ".git" -not -path "*/.terragrunt-cache/*" | xargs dirname | fzf)'
alias repos='repo'
alias tf='terraform'
alias tg='terragrunt'
alias vi='nvim'
