[window]
title = "Terminal"

[font]
size = 12

[font.normal]
family = "Inconsolata Nerd Font"
style = "Regular"

[colors.primary]
background = "#1a1a1a"
foreground = "#e0e0e0"

[colors.cursor]
cursor = "#e0e0e0"
text = "#1a1a1a"

[colors.normal]
black = "#303030"
blue = "#3b8eea"
cyan = "#20c5c5"
green = "#5ac550"
magenta = "#bf68bf"
red = "#d83838"
white = "#b0b0c0"
yellow = "#e6c446"

[colors.bright]
black = "#5c5c5c"
blue = "#6aa9fa"
cyan = "#67e6e6"
green = "#7ed876"
magenta = "#e57fe5"
red = "#f25a5a"
white = "#ededed"
yellow = "#f3d87e"

[colors.selection]
background = "#4a4d52"
text = "#e0e0e0"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "Home", mods = "Shift", action = "Paste" },
]
